.PHONY: clean All

All:
	@echo "----------Building project:[ asd - Debug ]----------"
	@cd "C:\Users\Victo\OneDrive - Universidad de Alcala\UNI\Año 2\Data Structures\Lab\helloworld\asd" && "$(MAKE)" -f  "asd.mk"
clean:
	@echo "----------Cleaning project:[ asd - Debug ]----------"
	@cd "C:\Users\Victo\OneDrive - Universidad de Alcala\UNI\Año 2\Data Structures\Lab\helloworld\asd" && "$(MAKE)" -f  "asd.mk" clean
